### PR TITLE
Add some tests from sheer

### PR DESCRIPTION
**Pull request by kurtrwall**
Added template tests  and a filter test to sheerlike from sheer

@rosskarchner @dpford

### CODE REVIEW

**Comment by rosskarchner** [comment]
do the tests succeed under Python 2.7 on your machine?

(you can do tox-e py27 to skip the Python 3 stuff_

**Comment by kurtrwall** [comment]
Hmm well they failed the second and third time out of 5 test runs. Not sure what could be making the difference. I just ran the same command 5 times without changing anything.

**Comment by kurtrwall** [comment]
The travis build details 2 failing and one passing runs of the tests.

**Comment by rosskarchner** [comment]
I can replicate the sometimes-passing, sometimes-failing test.

What I think is going on, is that multidicts are unordered, so when we loop through multidict.keys(), sometimes planet will be first, sometimes category will. 

The choice, then is: make the code more predictable, or the test more flexible. Since the order doesn't ultimately matter(right?), I'd go with the second, I think.

**Pull request merged**
